/* automatically generated by rust-bindgen 0.59.2 */

pub const QPDF_MAJOR_VERSION: u32 = 10;
pub const QPDF_MINOR_VERSION: u32 = 6;
pub const QPDF_PATCH_VERSION: u32 = 3;
pub const QPDF_VERSION: &[u8; 7usize] = b"10.6.3\0";
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _VA_ALIGN: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 0;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const EPERM: u32 = 1;
pub const ENOENT: u32 = 2;
pub const ESRCH: u32 = 3;
pub const EINTR: u32 = 4;
pub const EIO: u32 = 5;
pub const ENXIO: u32 = 6;
pub const E2BIG: u32 = 7;
pub const ENOEXEC: u32 = 8;
pub const EBADF: u32 = 9;
pub const ECHILD: u32 = 10;
pub const EAGAIN: u32 = 11;
pub const ENOMEM: u32 = 12;
pub const EACCES: u32 = 13;
pub const EFAULT: u32 = 14;
pub const EBUSY: u32 = 16;
pub const EEXIST: u32 = 17;
pub const EXDEV: u32 = 18;
pub const ENODEV: u32 = 19;
pub const ENOTDIR: u32 = 20;
pub const EISDIR: u32 = 21;
pub const ENFILE: u32 = 23;
pub const EMFILE: u32 = 24;
pub const ENOTTY: u32 = 25;
pub const EFBIG: u32 = 27;
pub const ENOSPC: u32 = 28;
pub const ESPIPE: u32 = 29;
pub const EROFS: u32 = 30;
pub const EMLINK: u32 = 31;
pub const EPIPE: u32 = 32;
pub const EDOM: u32 = 33;
pub const EDEADLK: u32 = 36;
pub const ENAMETOOLONG: u32 = 38;
pub const ENOLCK: u32 = 39;
pub const ENOSYS: u32 = 40;
pub const ENOTEMPTY: u32 = 41;
pub const EINVAL: u32 = 22;
pub const ERANGE: u32 = 34;
pub const EILSEQ: u32 = 42;
pub const STRUNCATE: u32 = 80;
pub const EDEADLOCK: u32 = 36;
pub const EADDRINUSE: u32 = 100;
pub const EADDRNOTAVAIL: u32 = 101;
pub const EAFNOSUPPORT: u32 = 102;
pub const EALREADY: u32 = 103;
pub const EBADMSG: u32 = 104;
pub const ECANCELED: u32 = 105;
pub const ECONNABORTED: u32 = 106;
pub const ECONNREFUSED: u32 = 107;
pub const ECONNRESET: u32 = 108;
pub const EDESTADDRREQ: u32 = 109;
pub const EHOSTUNREACH: u32 = 110;
pub const EIDRM: u32 = 111;
pub const EINPROGRESS: u32 = 112;
pub const EISCONN: u32 = 113;
pub const ELOOP: u32 = 114;
pub const EMSGSIZE: u32 = 115;
pub const ENETDOWN: u32 = 116;
pub const ENETRESET: u32 = 117;
pub const ENETUNREACH: u32 = 118;
pub const ENOBUFS: u32 = 119;
pub const ENODATA: u32 = 120;
pub const ENOLINK: u32 = 121;
pub const ENOMSG: u32 = 122;
pub const ENOPROTOOPT: u32 = 123;
pub const ENOSR: u32 = 124;
pub const ENOSTR: u32 = 125;
pub const ENOTCONN: u32 = 126;
pub const ENOTRECOVERABLE: u32 = 127;
pub const ENOTSOCK: u32 = 128;
pub const ENOTSUP: u32 = 129;
pub const EOPNOTSUPP: u32 = 130;
pub const EOTHER: u32 = 131;
pub const EOVERFLOW: u32 = 132;
pub const EOWNERDEAD: u32 = 133;
pub const EPROTO: u32 = 134;
pub const EPROTONOSUPPORT: u32 = 135;
pub const EPROTOTYPE: u32 = 136;
pub const ETIME: u32 = 137;
pub const ETIMEDOUT: u32 = 138;
pub const ETXTBSY: u32 = 139;
pub const EWOULDBLOCK: u32 = 140;
pub const _NLSCMPERROR: u32 = 2147483647;
pub const QPDF_SUCCESS: u32 = 0;
pub const QPDF_WARNINGS: u32 = 1;
pub const QPDF_ERRORS: u32 = 2;
pub const QPDF_TRUE: u32 = 1;
pub const QPDF_FALSE: u32 = 0;
pub type qpdf_offset_t = ::std::os::raw::c_longlong;
pub const qpdf_error_code_e_qpdf_e_success: qpdf_error_code_e = 0;
pub const qpdf_error_code_e_qpdf_e_internal: qpdf_error_code_e = 1;
pub const qpdf_error_code_e_qpdf_e_system: qpdf_error_code_e = 2;
pub const qpdf_error_code_e_qpdf_e_unsupported: qpdf_error_code_e = 3;
pub const qpdf_error_code_e_qpdf_e_password: qpdf_error_code_e = 4;
pub const qpdf_error_code_e_qpdf_e_damaged_pdf: qpdf_error_code_e = 5;
pub const qpdf_error_code_e_qpdf_e_pages: qpdf_error_code_e = 6;
pub const qpdf_error_code_e_qpdf_e_object: qpdf_error_code_e = 7;
pub type qpdf_error_code_e = ::std::os::raw::c_int;
pub const qpdf_object_type_e_ot_uninitialized: qpdf_object_type_e = 0;
pub const qpdf_object_type_e_ot_reserved: qpdf_object_type_e = 1;
pub const qpdf_object_type_e_ot_null: qpdf_object_type_e = 2;
pub const qpdf_object_type_e_ot_boolean: qpdf_object_type_e = 3;
pub const qpdf_object_type_e_ot_integer: qpdf_object_type_e = 4;
pub const qpdf_object_type_e_ot_real: qpdf_object_type_e = 5;
pub const qpdf_object_type_e_ot_string: qpdf_object_type_e = 6;
pub const qpdf_object_type_e_ot_name: qpdf_object_type_e = 7;
pub const qpdf_object_type_e_ot_array: qpdf_object_type_e = 8;
pub const qpdf_object_type_e_ot_dictionary: qpdf_object_type_e = 9;
pub const qpdf_object_type_e_ot_stream: qpdf_object_type_e = 10;
pub const qpdf_object_type_e_ot_operator: qpdf_object_type_e = 11;
pub const qpdf_object_type_e_ot_inlineimage: qpdf_object_type_e = 12;
pub type qpdf_object_type_e = ::std::os::raw::c_int;
pub const qpdf_object_stream_e_qpdf_o_disable: qpdf_object_stream_e = 0;
pub const qpdf_object_stream_e_qpdf_o_preserve: qpdf_object_stream_e = 1;
pub const qpdf_object_stream_e_qpdf_o_generate: qpdf_object_stream_e = 2;
pub type qpdf_object_stream_e = ::std::os::raw::c_int;
pub const qpdf_stream_data_e_qpdf_s_uncompress: qpdf_stream_data_e = 0;
pub const qpdf_stream_data_e_qpdf_s_preserve: qpdf_stream_data_e = 1;
pub const qpdf_stream_data_e_qpdf_s_compress: qpdf_stream_data_e = 2;
pub type qpdf_stream_data_e = ::std::os::raw::c_int;
pub const qpdf_stream_encode_flags_e_qpdf_ef_compress: qpdf_stream_encode_flags_e = 1;
pub const qpdf_stream_encode_flags_e_qpdf_ef_normalize: qpdf_stream_encode_flags_e = 2;
pub type qpdf_stream_encode_flags_e = ::std::os::raw::c_int;
pub const qpdf_stream_decode_level_e_qpdf_dl_none: qpdf_stream_decode_level_e = 0;
pub const qpdf_stream_decode_level_e_qpdf_dl_generalized: qpdf_stream_decode_level_e = 1;
pub const qpdf_stream_decode_level_e_qpdf_dl_specialized: qpdf_stream_decode_level_e = 2;
pub const qpdf_stream_decode_level_e_qpdf_dl_all: qpdf_stream_decode_level_e = 3;
pub type qpdf_stream_decode_level_e = ::std::os::raw::c_int;
pub const qpdf_r3_print_e_qpdf_r3p_full: qpdf_r3_print_e = 0;
pub const qpdf_r3_print_e_qpdf_r3p_low: qpdf_r3_print_e = 1;
pub const qpdf_r3_print_e_qpdf_r3p_none: qpdf_r3_print_e = 2;
pub type qpdf_r3_print_e = ::std::os::raw::c_int;
pub const qpdf_r3_modify_e_qpdf_r3m_all: qpdf_r3_modify_e = 0;
pub const qpdf_r3_modify_e_qpdf_r3m_annotate: qpdf_r3_modify_e = 1;
pub const qpdf_r3_modify_e_qpdf_r3m_form: qpdf_r3_modify_e = 2;
pub const qpdf_r3_modify_e_qpdf_r3m_assembly: qpdf_r3_modify_e = 3;
pub const qpdf_r3_modify_e_qpdf_r3m_none: qpdf_r3_modify_e = 4;
pub type qpdf_r3_modify_e = ::std::os::raw::c_int;
pub const pdf_form_field_flag_e_ff_all_read_only: pdf_form_field_flag_e = 1;
pub const pdf_form_field_flag_e_ff_all_required: pdf_form_field_flag_e = 2;
pub const pdf_form_field_flag_e_ff_all_no_export: pdf_form_field_flag_e = 4;
pub const pdf_form_field_flag_e_ff_btn_no_toggle_off: pdf_form_field_flag_e = 16384;
pub const pdf_form_field_flag_e_ff_btn_radio: pdf_form_field_flag_e = 32768;
pub const pdf_form_field_flag_e_ff_btn_pushbutton: pdf_form_field_flag_e = 65536;
pub const pdf_form_field_flag_e_ff_btn_radios_in_unison: pdf_form_field_flag_e = 131072;
pub const pdf_form_field_flag_e_ff_tx_multiline: pdf_form_field_flag_e = 4096;
pub const pdf_form_field_flag_e_ff_tx_password: pdf_form_field_flag_e = 8192;
pub const pdf_form_field_flag_e_ff_tx_file_select: pdf_form_field_flag_e = 1048576;
pub const pdf_form_field_flag_e_ff_tx_do_not_spell_check: pdf_form_field_flag_e = 4194304;
pub const pdf_form_field_flag_e_ff_tx_do_not_scroll: pdf_form_field_flag_e = 8388608;
pub const pdf_form_field_flag_e_ff_tx_comb: pdf_form_field_flag_e = 16777216;
pub const pdf_form_field_flag_e_ff_tx_rich_text: pdf_form_field_flag_e = 33554432;
pub const pdf_form_field_flag_e_ff_ch_combo: pdf_form_field_flag_e = 131072;
pub const pdf_form_field_flag_e_ff_ch_edit: pdf_form_field_flag_e = 262144;
pub const pdf_form_field_flag_e_ff_ch_sort: pdf_form_field_flag_e = 524288;
pub const pdf_form_field_flag_e_ff_ch_multi_select: pdf_form_field_flag_e = 2097152;
pub const pdf_form_field_flag_e_ff_ch_do_not_spell_check: pdf_form_field_flag_e = 4194304;
pub const pdf_form_field_flag_e_ff_ch_commit_on_sel_change: pdf_form_field_flag_e = 67108864;
pub type pdf_form_field_flag_e = ::std::os::raw::c_int;
pub const pdf_annotation_flag_e_an_invisible: pdf_annotation_flag_e = 1;
pub const pdf_annotation_flag_e_an_hidden: pdf_annotation_flag_e = 2;
pub const pdf_annotation_flag_e_an_print: pdf_annotation_flag_e = 4;
pub const pdf_annotation_flag_e_an_no_zoom: pdf_annotation_flag_e = 8;
pub const pdf_annotation_flag_e_an_no_rotate: pdf_annotation_flag_e = 16;
pub const pdf_annotation_flag_e_an_no_view: pdf_annotation_flag_e = 32;
pub const pdf_annotation_flag_e_an_read_only: pdf_annotation_flag_e = 64;
pub const pdf_annotation_flag_e_an_locked: pdf_annotation_flag_e = 128;
pub const pdf_annotation_flag_e_an_toggle_no_view: pdf_annotation_flag_e = 256;
pub const pdf_annotation_flag_e_an_locked_contents: pdf_annotation_flag_e = 512;
pub type pdf_annotation_flag_e = ::std::os::raw::c_int;
pub const qpdf_encryption_status_e_qpdf_es_encrypted: qpdf_encryption_status_e = 1;
pub const qpdf_encryption_status_e_qpdf_es_password_incorrect: qpdf_encryption_status_e = 2;
pub type qpdf_encryption_status_e = ::std::os::raw::c_int;
pub type va_list = *mut ::std::os::raw::c_char;
extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type size_t = ::std::os::raw::c_ulonglong;
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
extern "C" {
    pub fn __security_init_cookie();
}
extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize);
}
extern "C" {
    pub static mut __security_cookie: usize;
}
pub type __crt_bool = bool;
extern "C" {
    pub fn _invalid_parameter_noinfo();
}
extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn();
}
extern "C" {
    pub fn _invoke_watson(
        arg1: *const wchar_t,
        arg2: *const wchar_t,
        arg3: *const wchar_t,
        arg4: ::std::os::raw::c_uint,
        arg5: usize,
    );
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[test]
fn bindgen_test_layout___crt_locale_data_public() {
    assert_eq!(
        ::std::mem::size_of::<__crt_locale_data_public>(),
        16usize,
        concat!("Size of: ", stringify!(__crt_locale_data_public))
    );
    assert_eq!(
        ::std::mem::align_of::<__crt_locale_data_public>(),
        8usize,
        concat!("Alignment of ", stringify!(__crt_locale_data_public))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__crt_locale_data_public>()))._locale_pctype as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__crt_locale_data_public),
            "::",
            stringify!(_locale_pctype)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__crt_locale_data_public>()))._locale_mb_cur_max as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__crt_locale_data_public),
            "::",
            stringify!(_locale_mb_cur_max)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__crt_locale_data_public>()))._locale_lc_codepage as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(__crt_locale_data_public),
            "::",
            stringify!(_locale_lc_codepage)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data,
}
#[test]
fn bindgen_test_layout___crt_locale_pointers() {
    assert_eq!(
        ::std::mem::size_of::<__crt_locale_pointers>(),
        16usize,
        concat!("Size of: ", stringify!(__crt_locale_pointers))
    );
    assert_eq!(
        ::std::mem::align_of::<__crt_locale_pointers>(),
        8usize,
        concat!("Alignment of ", stringify!(__crt_locale_pointers))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__crt_locale_pointers>())).locinfo as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__crt_locale_pointers),
            "::",
            stringify!(locinfo)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__crt_locale_pointers>())).mbcinfo as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__crt_locale_pointers),
            "::",
            stringify!(mbcinfo)
        )
    );
}
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort,
}
#[test]
fn bindgen_test_layout__Mbstatet() {
    assert_eq!(
        ::std::mem::size_of::<_Mbstatet>(),
        8usize,
        concat!("Size of: ", stringify!(_Mbstatet))
    );
    assert_eq!(
        ::std::mem::align_of::<_Mbstatet>(),
        4usize,
        concat!("Alignment of ", stringify!(_Mbstatet))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_Mbstatet>()))._Wchar as *const _ as usize },
        0usize,
        concat!("Offset of field: ", stringify!(_Mbstatet), "::", stringify!(_Wchar))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_Mbstatet>()))._Byte as *const _ as usize },
        4usize,
        concat!("Offset of field: ", stringify!(_Mbstatet), "::", stringify!(_Byte))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_Mbstatet>()))._State as *const _ as usize },
        6usize,
        concat!("Offset of field: ", stringify!(_Mbstatet), "::", stringify!(_State))
    );
}
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = size_t;
extern "C" {
    pub fn _errno() -> *mut ::std::os::raw::c_int;
}
extern "C" {
    pub fn _set_errno(_Value: ::std::os::raw::c_int) -> errno_t;
}
extern "C" {
    pub fn _get_errno(_Value: *mut ::std::os::raw::c_int) -> errno_t;
}
extern "C" {
    pub fn __doserrno() -> *mut ::std::os::raw::c_ulong;
}
extern "C" {
    pub fn _set_doserrno(_Value: ::std::os::raw::c_ulong) -> errno_t;
}
extern "C" {
    pub fn _get_doserrno(_Value: *mut ::std::os::raw::c_ulong) -> errno_t;
}
extern "C" {
    pub fn memchr(
        _Buf: *const ::std::os::raw::c_void,
        _Val: ::std::os::raw::c_int,
        _MaxCount: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn memcmp(
        _Buf1: *const ::std::os::raw::c_void,
        _Buf2: *const ::std::os::raw::c_void,
        _Size: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn memcpy(
        _Dst: *mut ::std::os::raw::c_void,
        _Src: *const ::std::os::raw::c_void,
        _Size: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn memmove(
        _Dst: *mut ::std::os::raw::c_void,
        _Src: *const ::std::os::raw::c_void,
        _Size: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn memset(
        _Dst: *mut ::std::os::raw::c_void,
        _Val: ::std::os::raw::c_int,
        _Size: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn strchr(_Str: *const ::std::os::raw::c_char, _Val: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strrchr(_Str: *const ::std::os::raw::c_char, _Ch: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strstr(
        _Str: *const ::std::os::raw::c_char,
        _SubStr: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn wcschr(
        _Str: *const ::std::os::raw::c_ushort,
        _Ch: ::std::os::raw::c_ushort,
    ) -> *mut ::std::os::raw::c_ushort;
}
extern "C" {
    pub fn wcsrchr(_Str: *const wchar_t, _Ch: wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsstr(_Str: *const wchar_t, _SubStr: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _memicmp(
        _Buf1: *const ::std::os::raw::c_void,
        _Buf2: *const ::std::os::raw::c_void,
        _Size: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _memicmp_l(
        _Buf1: *const ::std::os::raw::c_void,
        _Buf2: *const ::std::os::raw::c_void,
        _Size: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn memccpy(
        _Dst: *mut ::std::os::raw::c_void,
        _Src: *const ::std::os::raw::c_void,
        _Val: ::std::os::raw::c_int,
        _Size: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn memicmp(
        _Buf1: *const ::std::os::raw::c_void,
        _Buf2: *const ::std::os::raw::c_void,
        _Size: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcscat_s(_Destination: *mut wchar_t, _SizeInWords: rsize_t, _Source: *const wchar_t) -> errno_t;
}
extern "C" {
    pub fn wcscpy_s(_Destination: *mut wchar_t, _SizeInWords: rsize_t, _Source: *const wchar_t) -> errno_t;
}
extern "C" {
    pub fn wcsncat_s(
        _Destination: *mut wchar_t,
        _SizeInWords: rsize_t,
        _Source: *const wchar_t,
        _MaxCount: rsize_t,
    ) -> errno_t;
}
extern "C" {
    pub fn wcsncpy_s(
        _Destination: *mut wchar_t,
        _SizeInWords: rsize_t,
        _Source: *const wchar_t,
        _MaxCount: rsize_t,
    ) -> errno_t;
}
extern "C" {
    pub fn wcstok_s(_String: *mut wchar_t, _Delimiter: *const wchar_t, _Context: *mut *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcsdup(_String: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcscat(_Destination: *mut wchar_t, _Source: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcscmp(
        _String1: *const ::std::os::raw::c_ushort,
        _String2: *const ::std::os::raw::c_ushort,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcscpy(_Destination: *mut wchar_t, _Source: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcscspn(_String: *const wchar_t, _Control: *const wchar_t) -> size_t;
}
extern "C" {
    pub fn wcslen(_String: *const ::std::os::raw::c_ushort) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn wcsnlen(_Source: *const wchar_t, _MaxCount: size_t) -> size_t;
}
extern "C" {
    pub fn wcsncat(_Destination: *mut wchar_t, _Source: *const wchar_t, _Count: size_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsncmp(
        _String1: *const ::std::os::raw::c_ushort,
        _String2: *const ::std::os::raw::c_ushort,
        _MaxCount: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcsncpy(_Destination: *mut wchar_t, _Source: *const wchar_t, _Count: size_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcspbrk(_String: *const wchar_t, _Control: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsspn(_String: *const wchar_t, _Control: *const wchar_t) -> size_t;
}
extern "C" {
    pub fn wcstok(_String: *mut wchar_t, _Delimiter: *const wchar_t, _Context: *mut *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcserror(_ErrorNumber: ::std::os::raw::c_int) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcserror_s(_Buffer: *mut wchar_t, _SizeInWords: size_t, _ErrorNumber: ::std::os::raw::c_int) -> errno_t;
}
extern "C" {
    pub fn __wcserror(_String: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn __wcserror_s(_Buffer: *mut wchar_t, _SizeInWords: size_t, _ErrorMessage: *const wchar_t) -> errno_t;
}
extern "C" {
    pub fn _wcsicmp(_String1: *const wchar_t, _String2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsicmp_l(_String1: *const wchar_t, _String2: *const wchar_t, _Locale: _locale_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsnicmp(_String1: *const wchar_t, _String2: *const wchar_t, _MaxCount: size_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsnicmp_l(
        _String1: *const wchar_t,
        _String2: *const wchar_t,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsnset_s(_Destination: *mut wchar_t, _SizeInWords: size_t, _Value: wchar_t, _MaxCount: size_t) -> errno_t;
}
extern "C" {
    pub fn _wcsnset(_String: *mut wchar_t, _Value: wchar_t, _MaxCount: size_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcsrev(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcsset_s(_Destination: *mut wchar_t, _SizeInWords: size_t, _Value: wchar_t) -> errno_t;
}
extern "C" {
    pub fn _wcsset(_String: *mut wchar_t, _Value: wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcslwr_s(_String: *mut wchar_t, _SizeInWords: size_t) -> errno_t;
}
extern "C" {
    pub fn _wcslwr(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcslwr_s_l(_String: *mut wchar_t, _SizeInWords: size_t, _Locale: _locale_t) -> errno_t;
}
extern "C" {
    pub fn _wcslwr_l(_String: *mut wchar_t, _Locale: _locale_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcsupr_s(_String: *mut wchar_t, _Size: size_t) -> errno_t;
}
extern "C" {
    pub fn _wcsupr(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn _wcsupr_s_l(_String: *mut wchar_t, _Size: size_t, _Locale: _locale_t) -> errno_t;
}
extern "C" {
    pub fn _wcsupr_l(_String: *mut wchar_t, _Locale: _locale_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsxfrm(_Destination: *mut wchar_t, _Source: *const wchar_t, _MaxCount: size_t) -> size_t;
}
extern "C" {
    pub fn _wcsxfrm_l(
        _Destination: *mut wchar_t,
        _Source: *const wchar_t,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> size_t;
}
extern "C" {
    pub fn wcscoll(_String1: *const wchar_t, _String2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcscoll_l(_String1: *const wchar_t, _String2: *const wchar_t, _Locale: _locale_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsicoll(_String1: *const wchar_t, _String2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsicoll_l(_String1: *const wchar_t, _String2: *const wchar_t, _Locale: _locale_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsncoll(_String1: *const wchar_t, _String2: *const wchar_t, _MaxCount: size_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsncoll_l(
        _String1: *const wchar_t,
        _String2: *const wchar_t,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsnicoll(_String1: *const wchar_t, _String2: *const wchar_t, _MaxCount: size_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _wcsnicoll_l(
        _String1: *const wchar_t,
        _String2: *const wchar_t,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcsdup(_String: *const wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsicmp(_String1: *const wchar_t, _String2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcsnicmp(_String1: *const wchar_t, _String2: *const wchar_t, _MaxCount: size_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn wcsnset(_String: *mut wchar_t, _Value: wchar_t, _MaxCount: size_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsrev(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsset(_String: *mut wchar_t, _Value: wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcslwr(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsupr(_String: *mut wchar_t) -> *mut wchar_t;
}
extern "C" {
    pub fn wcsicoll(_String1: *const wchar_t, _String2: *const wchar_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strcpy_s(
        _Destination: *mut ::std::os::raw::c_char,
        _SizeInBytes: rsize_t,
        _Source: *const ::std::os::raw::c_char,
    ) -> errno_t;
}
extern "C" {
    pub fn strcat_s(
        _Destination: *mut ::std::os::raw::c_char,
        _SizeInBytes: rsize_t,
        _Source: *const ::std::os::raw::c_char,
    ) -> errno_t;
}
extern "C" {
    pub fn strerror_s(
        _Buffer: *mut ::std::os::raw::c_char,
        _SizeInBytes: size_t,
        _ErrorNumber: ::std::os::raw::c_int,
    ) -> errno_t;
}
extern "C" {
    pub fn strncat_s(
        _Destination: *mut ::std::os::raw::c_char,
        _SizeInBytes: rsize_t,
        _Source: *const ::std::os::raw::c_char,
        _MaxCount: rsize_t,
    ) -> errno_t;
}
extern "C" {
    pub fn strncpy_s(
        _Destination: *mut ::std::os::raw::c_char,
        _SizeInBytes: rsize_t,
        _Source: *const ::std::os::raw::c_char,
        _MaxCount: rsize_t,
    ) -> errno_t;
}
extern "C" {
    pub fn strtok_s(
        _String: *mut ::std::os::raw::c_char,
        _Delimiter: *const ::std::os::raw::c_char,
        _Context: *mut *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _memccpy(
        _Dst: *mut ::std::os::raw::c_void,
        _Src: *const ::std::os::raw::c_void,
        _Val: ::std::os::raw::c_int,
        _MaxCount: size_t,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn strcat(
        _Destination: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strcmp(_Str1: *const ::std::os::raw::c_char, _Str2: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strcmpi(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strcoll(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strcoll_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strcpy(
        _Dest: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strcspn(
        _Str: *const ::std::os::raw::c_char,
        _Control: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn _strdup(_Source: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strerror(_ErrorMessage: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strerror_s(
        _Buffer: *mut ::std::os::raw::c_char,
        _SizeInBytes: size_t,
        _ErrorMessage: *const ::std::os::raw::c_char,
    ) -> errno_t;
}
extern "C" {
    pub fn strerror(_ErrorMessage: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _stricmp(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _stricoll(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _stricoll_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _stricmp_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strlen(_Str: *const ::std::os::raw::c_char) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn _strlwr_s(_String: *mut ::std::os::raw::c_char, _Size: size_t) -> errno_t;
}
extern "C" {
    pub fn _strlwr(_String: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strlwr_s_l(_String: *mut ::std::os::raw::c_char, _Size: size_t, _Locale: _locale_t) -> errno_t;
}
extern "C" {
    pub fn _strlwr_l(_String: *mut ::std::os::raw::c_char, _Locale: _locale_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strncat(
        _Dest: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
        _Count: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strncmp(
        _Str1: *const ::std::os::raw::c_char,
        _Str2: *const ::std::os::raw::c_char,
        _MaxCount: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strnicmp(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strnicmp_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strnicoll(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strnicoll_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strncoll(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn _strncoll_l(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn __strncnt(_String: *const ::std::os::raw::c_char, _Count: size_t) -> size_t;
}
extern "C" {
    pub fn strncpy(
        _Destination: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
        _Count: ::std::os::raw::c_ulonglong,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strnlen(_String: *const ::std::os::raw::c_char, _MaxCount: size_t) -> size_t;
}
extern "C" {
    pub fn _strnset(
        _Dest: *mut ::std::os::raw::c_char,
        _Val: ::std::os::raw::c_int,
        _Count: size_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strnset_s(
        _String: *mut ::std::os::raw::c_char,
        _SizeInBytes: size_t,
        _Value: ::std::os::raw::c_int,
        _MaxCount: size_t,
    ) -> errno_t;
}
extern "C" {
    pub fn strpbrk(
        _Str: *const ::std::os::raw::c_char,
        _Control: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strrev(_Str: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strset_s(
        _Destination: *mut ::std::os::raw::c_char,
        _DestinationSize: size_t,
        _Value: ::std::os::raw::c_int,
    ) -> errno_t;
}
extern "C" {
    pub fn _strset(
        _Destination: *mut ::std::os::raw::c_char,
        _Value: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strspn(
        _Str: *const ::std::os::raw::c_char,
        _Control: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn strtok(
        _String: *mut ::std::os::raw::c_char,
        _Delimiter: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strupr_s(_String: *mut ::std::os::raw::c_char, _Size: size_t) -> errno_t;
}
extern "C" {
    pub fn _strupr(_String: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn _strupr_s_l(_String: *mut ::std::os::raw::c_char, _Size: size_t, _Locale: _locale_t) -> errno_t;
}
extern "C" {
    pub fn _strupr_l(_String: *mut ::std::os::raw::c_char, _Locale: _locale_t) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strxfrm(
        _Destination: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
        _MaxCount: ::std::os::raw::c_ulonglong,
    ) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn _strxfrm_l(
        _Destination: *mut ::std::os::raw::c_char,
        _Source: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
        _Locale: _locale_t,
    ) -> size_t;
}
extern "C" {
    pub fn strdup(_String: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strcmpi(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn stricmp(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strlwr(_String: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strnicmp(
        _String1: *const ::std::os::raw::c_char,
        _String2: *const ::std::os::raw::c_char,
        _MaxCount: size_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn strnset(
        _String: *mut ::std::os::raw::c_char,
        _Value: ::std::os::raw::c_int,
        _MaxCount: size_t,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strrev(_String: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strset(_String: *mut ::std::os::raw::c_char, _Value: ::std::os::raw::c_int) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn strupr(_String: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _qpdf_data {
    _unused: [u8; 0],
}
pub type qpdf_data = *mut _qpdf_data;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _qpdf_error {
    _unused: [u8; 0],
}
pub type qpdf_error = *mut _qpdf_error;
pub type QPDF_ERROR_CODE = ::std::os::raw::c_int;
pub type QPDF_BOOL = ::std::os::raw::c_int;
extern "C" {
    pub fn qpdf_silence_errors(qpdf: qpdf_data);
}
extern "C" {
    pub fn qpdf_get_qpdf_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_init() -> qpdf_data;
}
extern "C" {
    pub fn qpdf_cleanup(qpdf: *mut qpdf_data);
}
extern "C" {
    pub fn qpdf_has_error(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_get_error(qpdf: qpdf_data) -> qpdf_error;
}
extern "C" {
    pub fn qpdf_more_warnings(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_next_warning(qpdf: qpdf_data) -> qpdf_error;
}
extern "C" {
    pub fn qpdf_get_error_full_text(q: qpdf_data, e: qpdf_error) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_get_error_code(q: qpdf_data, e: qpdf_error) -> qpdf_error_code_e;
}
extern "C" {
    pub fn qpdf_get_error_filename(q: qpdf_data, e: qpdf_error) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_get_error_file_position(q: qpdf_data, e: qpdf_error) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn qpdf_get_error_message_detail(q: qpdf_data, e: qpdf_error) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_set_suppress_warnings(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_check_pdf(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_set_ignore_xref_streams(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_attempt_recovery(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_read(
        qpdf: qpdf_data,
        filename: *const ::std::os::raw::c_char,
        password: *const ::std::os::raw::c_char,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_read_memory(
        qpdf: qpdf_data,
        description: *const ::std::os::raw::c_char,
        buffer: *const ::std::os::raw::c_char,
        size: ::std::os::raw::c_ulonglong,
        password: *const ::std::os::raw::c_char,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_empty_pdf(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_get_pdf_version(qpdf: qpdf_data) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_get_pdf_extension_level(qpdf: qpdf_data) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_get_user_password(qpdf: qpdf_data) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_get_info_key(qpdf: qpdf_data, key: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_set_info_key(qpdf: qpdf_data, key: *const ::std::os::raw::c_char, value: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn qpdf_is_linearized(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_is_encrypted(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_accessibility(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_extract_all(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_print_low_res(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_print_high_res(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_modify_assembly(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_modify_form(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_modify_annotation(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_modify_other(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_allow_modify_all(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_init_write(qpdf: qpdf_data, filename: *const ::std::os::raw::c_char) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_init_write_memory(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_get_buffer_length(qpdf: qpdf_data) -> size_t;
}
extern "C" {
    pub fn qpdf_get_buffer(qpdf: qpdf_data) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn qpdf_set_object_stream_mode(qpdf: qpdf_data, mode: qpdf_object_stream_e);
}
extern "C" {
    pub fn qpdf_set_stream_data_mode(qpdf: qpdf_data, mode: qpdf_stream_data_e);
}
extern "C" {
    pub fn qpdf_set_compress_streams(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_decode_level(qpdf: qpdf_data, level: qpdf_stream_decode_level_e);
}
extern "C" {
    pub fn qpdf_set_preserve_unreferenced_objects(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_newline_before_endstream(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_content_normalization(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_qdf_mode(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_deterministic_ID(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_static_ID(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_static_aes_IV(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_suppress_original_object_IDs(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_preserve_encryption(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_r2_encryption_parameters(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_print: QPDF_BOOL,
        allow_modify: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        allow_annotate: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r3_encryption_parameters2(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        allow_assemble: QPDF_BOOL,
        allow_annotate_and_form: QPDF_BOOL,
        allow_form_filling: QPDF_BOOL,
        allow_modify_other: QPDF_BOOL,
        print: qpdf_r3_print_e,
    );
}
extern "C" {
    pub fn qpdf_set_r4_encryption_parameters2(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        allow_assemble: QPDF_BOOL,
        allow_annotate_and_form: QPDF_BOOL,
        allow_form_filling: QPDF_BOOL,
        allow_modify_other: QPDF_BOOL,
        print: qpdf_r3_print_e,
        encrypt_metadata: QPDF_BOOL,
        use_aes: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r5_encryption_parameters2(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        allow_assemble: QPDF_BOOL,
        allow_annotate_and_form: QPDF_BOOL,
        allow_form_filling: QPDF_BOOL,
        allow_modify_other: QPDF_BOOL,
        print: qpdf_r3_print_e,
        encrypt_metadata: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r6_encryption_parameters2(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        allow_assemble: QPDF_BOOL,
        allow_annotate_and_form: QPDF_BOOL,
        allow_form_filling: QPDF_BOOL,
        allow_modify_other: QPDF_BOOL,
        print: qpdf_r3_print_e,
        encrypt_metadata: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r3_encryption_parameters(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        print: qpdf_r3_print_e,
        modify: qpdf_r3_modify_e,
    );
}
extern "C" {
    pub fn qpdf_set_r4_encryption_parameters(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        print: qpdf_r3_print_e,
        modify: qpdf_r3_modify_e,
        encrypt_metadata: QPDF_BOOL,
        use_aes: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r5_encryption_parameters(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        print: qpdf_r3_print_e,
        modify: qpdf_r3_modify_e,
        encrypt_metadata: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_r6_encryption_parameters(
        qpdf: qpdf_data,
        user_password: *const ::std::os::raw::c_char,
        owner_password: *const ::std::os::raw::c_char,
        allow_accessibility: QPDF_BOOL,
        allow_extract: QPDF_BOOL,
        print: qpdf_r3_print_e,
        modify: qpdf_r3_modify_e,
        encrypt_metadata: QPDF_BOOL,
    );
}
extern "C" {
    pub fn qpdf_set_linearization(qpdf: qpdf_data, value: QPDF_BOOL);
}
extern "C" {
    pub fn qpdf_set_minimum_pdf_version(qpdf: qpdf_data, version: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn qpdf_set_minimum_pdf_version_and_extension(
        qpdf: qpdf_data,
        version: *const ::std::os::raw::c_char,
        extension_level: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn qpdf_force_pdf_version(qpdf: qpdf_data, version: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn qpdf_force_pdf_version_and_extension(
        qpdf: qpdf_data,
        version: *const ::std::os::raw::c_char,
        extension_level: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn qpdf_register_progress_reporter(
        qpdf: qpdf_data,
        report_progress: ::std::option::Option<
            unsafe extern "C" fn(percent: ::std::os::raw::c_int, data: *mut ::std::os::raw::c_void),
        >,
        data: *mut ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn qpdf_write(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
pub type qpdf_oh = ::std::os::raw::c_uint;
extern "C" {
    pub fn qpdf_oh_release(qpdf: qpdf_data, oh: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_release_all(qpdf: qpdf_data);
}
extern "C" {
    pub fn qpdf_oh_new_object(qpdf: qpdf_data, oh: qpdf_oh) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_get_trailer(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_get_root(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_get_object_by_id(
        qpdf: qpdf_data,
        objid: ::std::os::raw::c_int,
        generation: ::std::os::raw::c_int,
    ) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_make_indirect_object(qpdf: qpdf_data, oh: qpdf_oh) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_replace_object(
        qpdf: qpdf_data,
        objid: ::std::os::raw::c_int,
        generation: ::std::os::raw::c_int,
        oh: qpdf_oh,
    );
}
extern "C" {
    pub fn qpdf_oh_is_initialized(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_bool(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_null(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_integer(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_real(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_name(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_string(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_operator(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_inline_image(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_array(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_dictionary(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_stream(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_indirect(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_scalar(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_name_and_equals(qpdf: qpdf_data, oh: qpdf_oh, name: *const ::std::os::raw::c_char) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_dictionary_of_type(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        type_: *const ::std::os::raw::c_char,
        subtype: *const ::std::os::raw::c_char,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_type_code(qpdf: qpdf_data, oh: qpdf_oh) -> qpdf_object_type_e;
}
extern "C" {
    pub fn qpdf_oh_get_type_name(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_wrap_in_array(qpdf: qpdf_data, oh: qpdf_oh) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_parse(qpdf: qpdf_data, object_str: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_get_bool_value(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_bool(qpdf: qpdf_data, oh: qpdf_oh, value: *mut QPDF_BOOL) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_int_value(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_longlong(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut ::std::os::raw::c_longlong,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_int_value_as_int(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_int(qpdf: qpdf_data, oh: qpdf_oh, value: *mut ::std::os::raw::c_int) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_uint_value(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_ulonglong;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_ulonglong(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut ::std::os::raw::c_ulonglong,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_uint_value_as_uint(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_uint(qpdf: qpdf_data, oh: qpdf_oh, value: *mut ::std::os::raw::c_uint) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_real_value(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_real(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut *const ::std::os::raw::c_char,
        length: *mut size_t,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_is_number(qpdf: qpdf_data, oh: qpdf_oh) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_numeric_value(qpdf: qpdf_data, oh: qpdf_oh) -> f64;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_number(qpdf: qpdf_data, oh: qpdf_oh, value: *mut f64) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_name(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_name(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut *const ::std::os::raw::c_char,
        length: *mut size_t,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_get_last_string_length(qpdf: qpdf_data) -> size_t;
}
extern "C" {
    pub fn qpdf_oh_get_string_value(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_string(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut *const ::std::os::raw::c_char,
        length: *mut size_t,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_utf8_value(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_value_as_utf8(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        value: *mut *const ::std::os::raw::c_char,
        length: *mut size_t,
    ) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_binary_string_value(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        length: *mut size_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_binary_utf8_value(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        length: *mut size_t,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_get_array_n_items(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_oh_get_array_item(qpdf: qpdf_data, oh: qpdf_oh, n: ::std::os::raw::c_int) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_begin_dict_key_iter(qpdf: qpdf_data, dict: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_dict_more_keys(qpdf: qpdf_data) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_dict_next_key(qpdf: qpdf_data) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_has_key(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_get_key(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_get_key_if_dict(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_is_or_has_name(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char) -> QPDF_BOOL;
}
extern "C" {
    pub fn qpdf_oh_new_uninitialized(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_null(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_bool(qpdf: qpdf_data, value: QPDF_BOOL) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_integer(qpdf: qpdf_data, value: ::std::os::raw::c_longlong) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_real_from_string(qpdf: qpdf_data, value: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_real_from_double(qpdf: qpdf_data, value: f64, decimal_places: ::std::os::raw::c_int) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_name(qpdf: qpdf_data, name: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_string(qpdf: qpdf_data, str_: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_unicode_string(qpdf: qpdf_data, utf8_str: *const ::std::os::raw::c_char) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_binary_string(qpdf: qpdf_data, str_: *const ::std::os::raw::c_char, length: size_t) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_binary_unicode_string(
        qpdf: qpdf_data,
        str_: *const ::std::os::raw::c_char,
        length: size_t,
    ) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_array(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_dictionary(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_new_stream(qpdf: qpdf_data) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_make_direct(qpdf: qpdf_data, oh: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_set_array_item(qpdf: qpdf_data, oh: qpdf_oh, at: ::std::os::raw::c_int, item: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_insert_item(qpdf: qpdf_data, oh: qpdf_oh, at: ::std::os::raw::c_int, item: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_append_item(qpdf: qpdf_data, oh: qpdf_oh, item: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_erase_item(qpdf: qpdf_data, oh: qpdf_oh, at: ::std::os::raw::c_int);
}
extern "C" {
    pub fn qpdf_oh_replace_key(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char, item: qpdf_oh);
}
extern "C" {
    pub fn qpdf_oh_remove_key(qpdf: qpdf_data, oh: qpdf_oh, key: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn qpdf_oh_replace_or_remove_key(
        qpdf: qpdf_data,
        oh: qpdf_oh,
        key: *const ::std::os::raw::c_char,
        item: qpdf_oh,
    );
}
extern "C" {
    pub fn qpdf_oh_get_dict(qpdf: qpdf_data, oh: qpdf_oh) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_get_object_id(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_oh_get_generation(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_oh_unparse(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_unparse_resolved(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_unparse_binary(qpdf: qpdf_data, oh: qpdf_oh) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn qpdf_oh_copy_foreign_object(qpdf: qpdf_data, other_qpdf: qpdf_data, foreign_oh: qpdf_oh) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_oh_get_stream_data(
        qpdf: qpdf_data,
        stream_oh: qpdf_oh,
        decode_level: qpdf_stream_decode_level_e,
        filtered: *mut QPDF_BOOL,
        bufp: *mut *mut ::std::os::raw::c_uchar,
        len: *mut size_t,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_oh_get_page_content_data(
        qpdf: qpdf_data,
        page_oh: qpdf_oh,
        bufp: *mut *mut ::std::os::raw::c_uchar,
        len: *mut size_t,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_oh_replace_stream_data(
        qpdf: qpdf_data,
        stream_oh: qpdf_oh,
        buf: *const ::std::os::raw::c_uchar,
        len: size_t,
        filter: qpdf_oh,
        decode_parms: qpdf_oh,
    );
}
extern "C" {
    pub fn qpdf_get_num_pages(qpdf: qpdf_data) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_get_page_n(qpdf: qpdf_data, zero_based_index: size_t) -> qpdf_oh;
}
extern "C" {
    pub fn qpdf_update_all_pages_cache(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_find_page_by_id(
        qpdf: qpdf_data,
        objid: ::std::os::raw::c_int,
        generation: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_find_page_by_oh(qpdf: qpdf_data, oh: qpdf_oh) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn qpdf_push_inherited_attributes_to_page(qpdf: qpdf_data) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_add_page(
        qpdf: qpdf_data,
        newpage_qpdf: qpdf_data,
        newpage: qpdf_oh,
        first: QPDF_BOOL,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_add_page_at(
        qpdf: qpdf_data,
        newpage_qpdf: qpdf_data,
        newpage: qpdf_oh,
        before: QPDF_BOOL,
        refpage: qpdf_oh,
    ) -> QPDF_ERROR_CODE;
}
extern "C" {
    pub fn qpdf_remove_page(qpdf: qpdf_data, page: qpdf_oh) -> QPDF_ERROR_CODE;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8,
}
