name: CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: git submodule update --init
        shell: bash
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
        shell: bash
      - run: ci/build.bash cargo ${{ matrix.target }} vendor
        shell: bash
      - run: ci/test.bash cargo ${{ matrix.target }} vendor
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        channel: [stable]
        target:
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: git submodule update --init
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - run: ci/build.bash cargo ${{ matrix.target }} vendor
      - run: ci/test.bash cargo ${{ matrix.target }} vendor

    strategy:
      fail-fast: false
      matrix:
        channel: [stable]
        target:
          - x86_64-apple-darwin

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: git submodule update --init
      - run: sudo apt-get update && sudo apt-get install -yqq libqpdf-dev
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - run: ci/build.bash cargo ${{ matrix.target }}
      - run: ci/test.bash cargo ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        channel: [stable]
        target:
          - x86_64-unknown-linux-gnu
